name: Continuous Delivery ASP.NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish --runtime linux-arm --self-contained true -p:PublishSingleFile=true --output ~/publish 
      
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.1
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: 22
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localPath: '~/publish'
        remotePath: '~/publish'
