name: Continuous Delivery ASP.NET Core

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish DemoServer -c Release -p:PublishProfile=FolderProfile -o ./publish 
      
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USERNAME }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      
    - name: Stop the server
      run: ssh staging 'sudo systemctl stop boot_demo_server'

    - name: Check out the source
      run: |
        scp ./publish staging:./publish
        ssh staging 'sudo chmod 755 -r publish'

    - name: Start the server
      if: ${{ always() }}
      run: ssh staging 'sudo systemctl start boot_demo_server'
