name: Continuous Delivery ASP.NET Core

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish DemoServer -c Release -p:PublishProfile=FolderProfile -o ./publish 
      
    - name: View Home
      run: ls ./
      
    - name: View Publish Results
      run: ls ./publish
      
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.1
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 22
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        localPath: './publish'
        remotePath: './publish'
        
    - name: Reboot server service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: sudo systemctl restart boot_demo_server
